### PR TITLE
Added plugin for checking IBM/Lotus Domino db files without auth.

### PR DESCRIPTION
**Pull request by RealRancor**
Plugin mostly a copy of nikto_drupal.plugin, database files taken from the OpenVAS plugin http://plugins.openvas.org/nasl.php?oid=10629

Also added the db_drupal to the dbcheck as it has the same syntax as the db_domino.

### CODE REVIEW

**Comment by RealRancor** [comment]
TBD: Also report db files which requires authentication?

**Comment by sullo** [comment]
I didn't do any checking for duplicates, but... 
$ grep -c \.nsf db_tests
232

**Comment by RealRancor** [comment]
Arghhhs, i don't know how i did the search in the db_tests but i've only found two entries for .nsf files. :-/

Thought it might a good idea to check the banner first to avoid false positives. Will check later if there are any files missing from the db_domino and add it if not.

**Comment by sullo** [comment]
This is probably a better way--reduce FP and fewer checks on non-Domino servers... I was just pointing out the lists should be in sync... and then removed from db_tests!

**Comment by RealRancor** [comment]
Arghh, sorry. Completely misunderstood you :-)

So lets merge https://github.com/sullo/nikto/issues/318 and i will come up with a new PR for the plugin and the merged db_tests into db_domino.

**Comment by sullo** [comment]
#318 merged. 

No worries...but if we can keep overhead down using code you already wrote, lets do it!

**Pull request closed without merging**
