### PR TITLE
Add Gamatronic Power+ default credential

### PR DESCRIPTION
**Pull request by opt9**

### CODE REVIEW

**Comment by sullo** [comment]
The second field should be the actual "realm" name that matches against. Looks like that is formatted for a report output? The acct info will get populated if it matches.

**Comment by opt9** [comment]
"Power+ (default: admin/admin)" is the real realm. kkk. ;-)

**Comment by opt9** [comment]
Maybe developers wanted to help user remind the password.

**Comment by sullo** [comment]
That's awesome.

**Pull request merged**
