### PR TITLE
nikto_tests.plugin: Have content matching logic assume multi-line con…

### PR DESCRIPTION
**Pull request by datadiode**
…tent

I guess this reflects the original intention, because existing tests like the one for /.bash_history seem to make more sense this way.

### CODE REVIEW

**Comment by sullo** [comment]
Yes this does seem like it's better to match multiple line always. Question though, have you been running this way since you committed, and if so have there been more false positives? I'll have to test it out on a few sites but let me know what you've seen as well!

**Comment by datadiode** [comment]
I don't see any difference with my (very specific and limited, and by no means representative) pentest target.

**Comment by datadiode** [comment]
sub nikto_tests() calls unslash() for both headers and data.

**Comment by sullo** [comment]
> sub nikto_tests() calls unslash() for both headers and data.

True. However, nikto_tests() is not the only way nfetch() is called. Any case it's called from another location (e.g., another plugin) it may not get the unslash() called on data. The only way to ensure it's done on *every* request (that is correctly right by using nfetch()) is to put it in nfetch() itself.

I believe you _could_ add it to unslash() and then explicitly call unslash at line 2414 inside nfetch. That might be overkill for the other esapes, but it will cover the use case of data. (with exception next line noted)

Also, I don't recall why in nfetch it was /\\\"/\"/ (3 slashes before first quote) and in unslash it's /\\"/\"/ which tells me the data there is not the same. I suspect this is due to how it's represented in the CSV.

Here are examples of plugins calling nfetch():
```plugins$ grep -c nfetch *plugin|grep -v 0$
nikto_apache_expect_xss.plugin:1
nikto_apacheusers.plugin:5
nikto_cgi.plugin:1
nikto_clientaccesspolicy.plugin:2
nikto_core.plugin:14
nikto_dictionary_attack.plugin:1
nikto_dir_traversal.plugin:2
nikto_dishwasher.plugin:1
nikto_docker_registry.plugin:1
nikto_domino.plugin:6
nikto_drupal.plugin:2
nikto_embedded.plugin:1
nikto_favicon.plugin:3
nikto_headers.plugin:6
nikto_httpoptions.plugin:6
nikto_msgs.plugin:2
nikto_multiple_index.plugin:1
nikto_negotiate.plugin:1
nikto_origin_reflection.plugin:2
nikto_parked.plugin:1
nikto_paths.plugin:1
nikto_put_del_test.plugin:4
nikto_robots.plugin:2
nikto_shellshock.plugin:3
nikto_siebel.plugin:4
nikto_sitefiles.plugin:2
nikto_strutshock.plugin:1
nikto_tests.plugin:3```

**Comment by datadiode** [comment]
I think the 3rd backslash before the 1st quote is redundant, as is the backslash before the 2nd quote.

The reason for not calling unslash() inside nfetch() was that it would break content-length calculation done in nikto_tests(). A preferable approach may be to move both the call to unslash() and the content-length calculation to nfetch().

**Comment by sullo** [comment]
I don't know why I stopped looking at this, but yeah, doing the content length call right before sending would be best. I'll see if I can mash all this up.

**Pull request closed without merging**
