### PR TITLE
nikto_tests.plugin: Allow tests to specify multiple headers / Set content-length

### PR DESCRIPTION
**Pull request by datadiode**
Example for multiple headers:  
"Authorization: Basic dXNlcjpwYXNzd29yZA==\r\nSOAPAction: Authorized"

### CODE REVIEW

**Comment by sullo** [comment]
The example will only work if the db_tests headers portion is surrounded by single quotes and not double, I believe. This is ok I think, but it's worth noting--I don't see a way around it if \\r\\n is going to be the appropriate header delimiter.

**Comment by datadiode** [comment]
I wasn't aware that I could have used single quotes. They don't seem to make a difference though. It works either way for me.

**Comment by sullo** [comment]
So what is unslash doing specifically? what's an example of the header string for that?

Also, this bit
```
            my $header = unslash($TESTS{$checkid}{'headers'});
            if ($header) {
```

would be faster reversed, i think, like this where you only call unslash if needed.
```            
if ($TESTS{$checkid}{'headers'}) {
  my $header = unslash($TESTS{$checkid}{'headers'});
 [...]
}
```

**Comment by datadiode** [comment]
unslash() translates escape sequences like \r, \n, \t, \xC5, ... into respective characters.  
The notation used in above multiple header example remains valid.  
unslash() is also applied to request message bodies specified in the _HTTP Data_ field.

I preferred needlessly unslash()ing empty strings over doing redundant hash table lookups, but considering that the _HTTP Data_ and _Headers_ fields are empty most of the time, your revised code will surely run faster, by some non-zero amount. I haven't experienced any performance issues with that. You could also rewrite the code in a way that avoids both unslash()ing empty strings and redundant hash table lookups.

**Pull request merged**
