### PR TITLE
Clarify licensing terms

### PR DESCRIPTION
**Pull request by oxr463**
Source: https://github.com/sullo/nikto/blob/master/program/nikto.pl#L10
SPDX: GPL-2.0-only

### CODE REVIEW

**Comment by iasdeoupxe** [comment]
In #654 the following file existing license file was mention:

https://github.com/sullo/nikto/blob/master/program/docs/LICENSE.txt

Maybe that should be dropped as well?

**Comment by tautology0** [comment]
Okay, silly question: why does it matter whether the licence is in license.txt or copying?

**Comment by pombredanne** [comment]
> Okay, silly question: why does it matter whether the licence is in license.txt or copying?

It does not matter

**Comment by iasdeoupxe** [comment]
Probably the only difference is how github is seeing / showing the license as the one for the repo.

**Comment by oxr463** [comment]
There is no actual difference. However, naming the file `COPYING` is part of the [GNU standards][1]. The important part is the licensing section in the README which explicitely defines the license to be [`GPL-2.0.-only`][2].

[1]: https://www.gnu.org/prep/standards/standards.html#Releases
[2]: https://www.gnu.org/licenses/identify-licenses-clearly.html

**Pull request merged**
