### PR TITLE
Update logic to use less layers.

### PR DESCRIPTION
**Pull request by felipenazario**

### CODE REVIEW

**Comment by felipenazario** [comment]
Also is fixed a CVE at alpine image that comes without a defined password.

**Comment by sullo** [comment]
I'm not much of a docker user. @rodolof or @codingo can you confirm these changes are good?

**Comment by codingo** [comment]
I don't know enough about docker to verify this, sorry @sullo. @FranticFerret made the Subfinder docker file and may be able to review this.

**Comment by codingo** [comment]
Tagging @vortexau as he is also quite skilled in this area

**Comment by vortexau** [comment]
Does as described on the tin; uses a specific version of Alpine for the base, and then applies changes such as creating a nikto user and group, installing perl and nikto in a single command - resulting in a single layer. Included in that layer is setting a randomly generated root password for the container.

While I haven't run the container myself, it looks like a positive change and ensures updated nikto containers will be simpler to work with, and ensures the container has some basic protections against accessing the root account. 
My only minor concern, and this is due to not tested the container or nikto outside a default Kali install, is the presence of 'make' in the container. Unless specifically required for nikto, it should not be present.
Otherwise it's a solid improvement.

**Comment by felipenazario** [comment]
@vortexau, the list of installed packages was maintained from the previous Dockerfile version, I just consider the dependencies was already validated. But since you are arguing this, I will review the installed packages one by one. Accept this PR and then if necessary I will open another one.

**Comment by vortexau** [comment]
@felipenazario apologies - I wasn't trying to imply anything, I was just noting that it may not be needed. As you rightly say, the previous version included 'make' so it may well be there for good reason. It's up to @sullo if they're willing to accept the PR as it is - there may be a known reason for 'make' being present.

**Comment by sullo** [comment]
I would not know why it would need 'make' unless it was a dependency on installing perl (which I'm doubting). I'll accept and close the PR. Thank you all for submitting/reviewing!

**Pull request merged**
