### PR TITLE
Add Miele Professional PG 8528 directory traversal check

### PR DESCRIPTION
**Pull request by opt9**
BTW, can I add the server response header to 'Match1 And' ?

For example, 
"Server: PST10 WebServer"

### CODE REVIEW

**Comment by drwetter** [comment]
Sorry chiming in but isn't that a check which is already covered?

**Comment by sullo** [comment]
@drwetter it depends on if the number of /../ is specifically required (e.g., will it fail if there is one more?). 

@opt9 the header won't be checked on any of those, only the body content. To that point as well, I always go with "root:0" as it's less false-positive prone.

**Comment by opt9** [comment]
@drwetter @sullo If I can detect server response header in plugin, I want to delete this pattern and add a new plugin to check this hilarious dishwasher directory traversal vuln. 

I worry about the duplicate false alert, specifically 'programdb_tests: "006555" TP-Link directory traversal'

**Comment by sullo** [comment]
Again that might not matter, due to 006555 having /help/.. really depends on how they work. If you change it to "root:0" i'll merge it!

**Comment by sullo** [comment]
The pattern should work fine, but do you see *nix that have root without UID 0? /me just curious, i've never come across that.

**Comment by opt9** [comment]
It's /etc/shadow, not /etc/passwd. ;-)

cf. http://seclists.org/fulldisclosure/2017/Mar/63

**Comment by sullo** [comment]
I was so busy shaking my head over this dishwasher I didn't notice it was shadow, not passwd.

what i was thinking with your check, though was "root:\d:" should work too. but that got me into asking the question... going to blame the lack of coffee. it was noon but that excuse still works.

**Pull request merged**
