### PR TITLE
Added 403 result (forbidden) for server-status check

### PR DESCRIPTION
**Pull request by PeterMosmans**
Minor addition to increase fingerprinting for Apache servers when e.g. a ACL is active

### CODE REVIEW

**Comment by sullo** [comment]
I'm afraid this will false positive, and not sure exactly how this helps when testing a server. Can you elaborate on why this is a valuable test?  Thanks.

**Comment by PeterMosmans** [comment]
Hi,
I noticed that some servers having an ACL on that specific module (path) return 403 instead of 200 or 401. As far as I can tell this could help in determining the usage of an ACL and/or fingerprinting the server (module).
Note that there are already checks in place for 200 or 401 for server-status, so I don't know whether it's the right location...

**Comment by sullo** [comment]
Ahh yes, fingerprinting. I didn't think of that last night. What I'd do
here would be to change this guy:
"007018","0","b","/server-status","GET","401","","","","","Apache
server-status interface found (pass protected)","",""

to something like

"007018","0","b","/server-status","GET","401","403","","","","Apache
server-status interface found (pass protected)","",""

and change pass protected to something like ... "or forbidden"

that'll save us a request.


On Wed, Sep 2, 2015 at 10:08 PM, Peter Mosmans <notifications@github.com>
wrote:

> Hi,
> I noticed that some servers having an ACL on that specific module (path)
> return 403 instead of 200 or 401. As far as I can tell this could help in
> determining the usage of an ACL and/or fingerprinting the server (module).
> Note that there are already checks in place for 200 or 401 for
> server-status, so I don't know whether it's the right location...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sullo/nikto/pull/277#issuecomment-137301427>.
>



-- 

http://cirt.net     |      http://richsec.com/

**Comment by PeterMosmans** [comment]
Thanks for the feedback, now I finally know what these empty strings are for :)
Modified pullrequest.

**Comment by RealRancor** [comment]
@PeterMosmans @sullo 

On a todays scan of one server two results where shown:

```
+ /server-status: Apache server-status interface found (protected/forbidden)
+ OSVDB-561: /server-status: This reveals Apache information. Comment out appropriate line in the Apache conf file or restrict access to allowed sources.
```

The server itself is replying with an 200 on this check:

```
 curl -I 127.0.0.1/server-status

HTTP/1.1 200 OK
Date: Fri, 16 Oct 2015 11:43:17 GMT
Server: Apache/2.4.7 (Ubuntu)
Vary: Accept-Encoding
Content-Length: 4016
Content-Type: text/html; charset=ISO-8859-1
```

Currently i have no idea why this is happening.

**Comment by RealRancor** [comment]
Ah, never mind. Even after reverting this change by removing the 403 added here the same is shown. So just created a new issue https://github.com/sullo/nikto/issues/291

**Pull request merged**
