### PR TITLE
Add check for Dokuwiki VERSION file

### PR DESCRIPTION
**Pull request by RealRancor**
Content only contains a string like:

2014-09-29b "Hrun"

or

2011-05-25a "Rincewind"

### CODE REVIEW

**Comment by sullo** [comment]
Hmm, pretty concerned about this--I have a feeling it's going to match on a lot of 404 pages. The first bit of the regex is optional, and the second is a space and any "word" in quotes.

**Comment by RealRancor** [comment]
Argss, sorry. Messed up the regex, only the a-z should be optional. Will provide a fix tomorrow.

**Comment by sullo** [comment]
Reverted for now since github makes such things easy.

**Comment by RealRancor** [comment]
Thanks! New PR in https://github.com/sullo/nikto/pull/266

**Pull request merged**
