### PR TITLE
Add instructions for Docker container usage

### PR DESCRIPTION
**Pull request by NicolasCARPi**
Docker related documentation was missing.

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
@sullo Hello, can you have a look at this PR please :)

**Comment by sullo** [comment]
I rarely use Docker so I'm not fully qualified. @tautology0 or @mostafahussein would be better suited (I think) if they can.

**Comment by mostafahussein** [comment]
This is looks good to me, Can we just make it `Run as  a Docker container:` instead ?

**Comment by NicolasCARPi** [comment]
@mostafahussein Good remarks :) I've pushed another commit addressing them.

**Comment by mostafahussein** [comment]
@NicolasCARPi Great!, I would like to suggest having another example in case someone wanted to save the reports on the host.
So basically we need  to mount a volume and then specify the path on the host and inside the container so we can have a copy of reports when the scan is done
for example: 
```
-v /path/to/reports/on/host:/path/to/reports/inside/container
```
You can get more details about reports in nikto through this: https://cirt.net/nikto2-docs/reports.html.

**Comment by sullo** [comment]
I will accept the PR when you two are happy :100: 

This looks good so far, if we can get the last commented change in... that it for now?

**Comment by NicolasCARPi** [comment]
@mostafahussein I have added more examples of usage.

I chose to bind the volume to `/tmp` inside the container, because the default export dir is also the one with the program and mounting it would break things. `/tmp` is empty so it's a good fit for this purpose.

Note 1: nikto is executed as root in the container, this is something that should be addressed. The resulting exported file is owned by the root user of the host system.

Note 2: it seems the json export is broken, because the json is invalid, but that's for another issue :)

**Comment by sullo** [comment]
Ok so we good here for now? With some additional issues to open:

- JSON Export Invalid
- Nikto runs as root in Docker

**Comment by mostafahussein** [comment]
@sullo Yes and I am working on the user issue and some other modifications related to the reports file permissions that @NicolasCARPi  mentioned and I think the PR will be ready by tomorrow.

**Pull request merged**
